
GET http://localhost:3000/notes
###

POST http://localhost:3000/notes
Content-Type: application/json

{
    "noteText": "Ala ma kota 2",
    "noteDelay": 2,
    "timestamp": "2010-06-29T15:49:17.926Z"
}
